# Generated by Django 4.2.2 on 2023-06-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9)),
                ('opis', models.TextField(blank=True, max_length=1000)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjaogloszeniowa.kategoria')),
            ],
            options={
                'verbose_name': 'ogłoszenie',
                'verbose_name_plural': 'ogłoszenia',
            },
        ),
    ]
